# Capital Asset Pricing Model (CAPM)

In [3]:
%pip install yfinance pandas numpy matplotlib

Defaulting to user installation because normal site-packages is not writeable
Collecting yfinance
  Using cached yfinance-1.5.1-py2.py3-none-any.whl.metadata (6.2 kB)
Collecting pandas
  Downloading pandas-3.0.3-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting numpy
  Downloading numpy-2.5.1-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Collecting matplotlib
  Downloading matplotlib-3.11.0-cp314-cp314-win_amd64.whl.metadata (80 kB)
Requirement already satisfied: requests>=2.31 in C:\Users\SMIT\AppData\Roaming\Python\Python314\site-packages (from yfinance) (2.34.2)
Collecting multitasking>=0.0.7 (from yfinance)
  Using cached multitasking-0.0.13-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: platformdirs>=2.0.0 in C:\Users\SMIT\AppData\Roaming\Python\Python314\site-packages (from yfinance) (4.10.0)
Collecting pytz>=2022.5 (from yfinance)
  Downloading pytz-2026.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting peewee>=3.16.2 (from yfinance)
  Using cached peewee-4.1.2-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: beautifulsoup4>=4.11.1 in C:\Users\SMIT\AppData\Roaming\Python\Python314\site-packages (from yfinance) (4.15.0)
Collecting curl_cffi>=0.15 (from yfinance)
  Using cached curl_cffi-0.15.0-cp310-abi3-win_amd64.whl.metadata (18 kB)
Collecting protobuf>=3.19.0 (from yfinance)
  Using cached protobuf-7.35.1-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Requirement already satisfied: websockets>=13.0 in C:\Users\SMIT\AppData\Roaming\Python\Python314\site-packages (from yfinance) (16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\SMIT\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\SMIT\AppData\Roaming\Python\Python314\site-packages (from pandas) (2026.2)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.3-cp314-cp314-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.63.0-cp314-cp314-win_amd64.whl.metadata (121 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.0-cp314-cp314-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: packaging>=20.0 in C:\Users\SMIT\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (26.2)
Collecting pillow>=9 (from matplotlib)
  Downloading pillow-12.3.0-cp314-cp314-win_amd64.whl.metadata (9.3 kB)
Collecting pyparsing>=3 (from matplotlib)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: soupsieve>=1.6.1 in C:\Users\SMIT\AppData\Roaming\Python\Python314\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8.4)
Requirement already satisfied: typing-extensions>=4.0.0 in C:\Users\SMIT\AppData\Roaming\Python\Python314\site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=2.0.0 in C:\Users\SMIT\AppData\Roaming\Python\Python314\site-packages (from curl_cffi>=0.15->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in C:\Users\SMIT\AppData\Roaming\Python\Python314\site-packages (from curl_cffi>=0.15->yfinance) (2026.5.20)
Requirement already satisfied: rich in C:\Users\SMIT\AppData\Roaming\Python\Python314\site-packages (from curl_cffi>=0.15->yfinance) (15.0.0)
Requirement already satisfied: pycparser in C:\Users\SMIT\AppData\Roaming\Python\Python314\site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (3.0)
Requirement already satisfied: six>=1.5 in C:\Users\SMIT\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\SMIT\AppData\Roaming\Python\Python314\site-packages (from requests>=2.31->yfinance) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\SMIT\AppData\Roaming\Python\Python314\site-packages (from requests>=2.31->yfinance) (3.15)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\SMIT\AppData\Roaming\Python\Python314\site-packages (from requests>=2.31->yfinance) (2.7.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in C:\Users\SMIT\AppData\Roaming\Python\Python314\site-packages (from rich->curl_cffi>=0.15->yfinance) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\SMIT\AppData\Roaming\Python\Python314\site-packages (from rich->curl_cffi>=0.15->yfinance) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in C:\Users\SMIT\AppData\Roaming\Python\Python314\site-packages (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.15->yfinance) (0.1.2)
Using cached yfinance-1.5.1-py2.py3-none-any.whl (144 kB)
Downloading pandas-3.0.3-cp314-cp314-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.9 MB 4.2 MB/s eta 0:00:03
   ------ --------------------------------- 1.6/9.9 MB 5.4 MB/s eta 0:00:02
   --------------- ------------------------ 3.9/9.9 MB 8.4 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.9 MB 14.2 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.9 MB 14.2 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.9 MB 14.2 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.9 MB 14.2 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.9 MB 14.2 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 6.1 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 5.5 MB/s  0:00:01
Downloading numpy-2.5.1-cp314-cp314-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   -------- ------------------------------- 2.6/12.6 MB 11.8 MB/s eta 0:00:01
   ------------------------------ --------- 9.4/12.6 MB 27.0 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.6 MB 21.3 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 19.4 MB/s  0:00:00
Downloading matplotlib-3.11.0-cp314-cp314-win_amd64.whl (9.5 MB)
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   --------------------- ------------------ 5.0/9.5 MB 24.2 MB/s eta 0:00:01
   ---------------------------------------  9.4/9.5 MB 24.9 MB/s eta 0:00:01
   ---------------------------------------- 9.5/9.5 MB 21.6 MB/s  0:00:00
Downloading contourpy-1.3.3-cp314-cp314-win_amd64.whl (232 kB)
Using cached curl_cffi-0.15.0-cp310-abi3-win_amd64.whl (1.7 MB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.63.0-cp314-cp314-win_amd64.whl (2.3 MB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 2.3/2.3 MB 15.7 MB/s  0:00:00
Downloading kiwisolver-1.5.0-cp314-cp314-win_amd64.whl (75 kB)
Using cached multitasking-0.0.13-py3-none-any.whl (16 kB)
Using cached peewee-4.1.2-py3-none-any.whl (173 kB)
Downloading pillow-12.3.0-cp314-cp314-win_amd64.whl (7.2 MB)
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   ---------------------------- ----------- 5.2/7.2 MB 26.1 MB/s eta 0:00:01
   ---------------------------------------- 7.2/7.2 MB 19.9 MB/s  0:00:00
Using cached protobuf-7.35.1-cp310-abi3-win_amd64.whl (439 kB)
Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
Downloading pytz-2026.2-py2.py3-none-any.whl (510 kB)
Installing collected packages: pytz, peewee, multitasking, pyparsing, protobuf, pillow, numpy, kiwisolver, fonttools, cycler, pandas, contourpy, matplotlib, curl_cffi, yfinance

   ----------------------------------------  0/15 [pytz]
   ----------------------------------------  0/15 [pytz]
   -- -------------------------------------  1/15 [peewee]
   -- -------------------------------------  1/15 [peewee]
   ----- ----------------------------------  2/15 [multitasking]
   -------- -------------------------------  3/15 [pyparsing]
   ---------- -----------------------------  4/15 [protobuf]
   ---------- -----------------------------  4/15 [protobuf]
   ---------- -----------------------------  4/15 [protobuf]
   ---------- -----------------------------  4/15 [protobuf]
   ---------- -----------------------------  4/15 [protobuf]
   ---------- -----------------------------  4/15 [protobuf]
   ------------- --------------------------  5/15 [pillow]
   ------------- --------------------------  5/15 [pillow]
   ------------- --------------------------  5/15 [pillow]
   ------------- --------------------------  5/15 [pillow]
   ------------- --------------------------  5/15 [pillow]
   ------------- --------------------------  5/15 [pillow]
   ------------- --------------------------  5/15 [pillow]
   ------------- --------------------------  5/15 [pillow]
   ------------- --------------------------  5/15 [pillow]
   ------------- --------------------------  5/15 [pillow]
   ------------- --------------------------  5/15 [pillow]
   ---------------- -----------------------  6/15 [numpy]
   ---------------- -----------------------  6/15 [numpy]
   ---------------- -----------------------  6/15 [numpy]
   ---------------- -----------------------  6/15 [numpy]
   ---------------- -----------------------  6/15 [numpy]
   ---------------- -----------------------  6/15 [numpy]
   ---------------- -----------------------  6/15 [numpy]
   ---------------- -----------------------  6/15 [numpy]
   ---------------- -----------------------  6/15 [numpy]
   ---------------- -----------------------  6/15 [numpy]
   ---------------- -----------------------  6/15 [numpy]
   ---------------- -----------------------  6/15 [numpy]
   ---------------- -----------------------  6/15 [numpy]
   ---------------- -----------------------  6/15 [numpy]
   ---------------- -----------------------  6/15 [numpy]
   ---------------- -----------------------  6/15 [numpy]
   ---------------- -----------------------  6/15 [numpy]
   ---------------- -----------------------  6/15 [numpy]
   ---------------- -----------------------  6/15 [numpy]
   ---------------- -----------------------  6/15 [numpy]
   ---------------- -----------------------  6/15 [numpy]
   ---------------- -----------------------  6/15 [numpy]
   ---------------- -----------------------  6/15 [numpy]
   ---------------- -----------------------  6/15 [numpy]
   ---------------- -----------------------  6/15 [numpy]
   ---------------- -----------------------  6/15 [numpy]
   ---------------- -----------------------  6/15 [numpy]
   ---------------- -----------------------  6/15 [numpy]
   ---------------- -----------------------  6/15 [numpy]
   ---------------- -----------------------  6/15 [numpy]
   ---------------- -----------------------  6/15 [numpy]
   ---------------- -----------------------  6/15 [numpy]
   ---------------- -----------------------  6/15 [numpy]
   ---------------- -----------------------  6/15 [numpy]
   ---------------- -----------------------  6/15 [numpy]
   ---------------- -----------------------  6/15 [numpy]
   ---------------- -----------------------  6/15 [numpy]
   ---------------- -----------------------  6/15 [numpy]
   ---------------- -----------------------  6/15 [numpy]
   ---------------- -----------------------  6/15 [numpy]
   ---------------- -----------------------  6/15 [numpy]
   ---------------- -----------------------  6/15 [numpy]
   ---------------- -----------------------  6/15 [numpy]
   ---------------- -----------------------  6/15 [numpy]
   ---------------- -----------------------  6/15 [numpy]
   ------------------ ---------------------  7/15 [kiwisolver]
   --------------------- ------------------  8/15 [fonttools]
   --------------------- ------------------  8/15 [fonttools]
   --------------------- ------------------  8/15 [fonttools]
   --------------------- ------------------  8/15 [fonttools]
   --------------------- ------------------  8/15 [fonttools]
   --------------------- ------------------  8/15 [fonttools]
   --------------------- ------------------  8/15 [fonttools]
   --------------------- ------------------  8/15 [fonttools]
   --------------------- ------------------  8/15 [fonttools]
   --------------------- ------------------  8/15 [fonttools]
   --------------------- ------------------  8/15 [fonttools]
   --------------------- ------------------  8/15 [fonttools]
   --------------------- ------------------  8/15 [fonttools]
   --------------------- ------------------  8/15 [fonttools]
   --------------------- ------------------  8/15 [fonttools]
   --------------------- ------------------  8/15 [fonttools]
   --------------------- ------------------  8/15 [fonttools]
   --------------------- ------------------  8/15 [fonttools]
   --------------------- ------------------  8/15 [fonttools]
   --------------------- ------------------  8/15 [fonttools]
   --------------------- ------------------  8/15 [fonttools]
   --------------------- ------------------  8/15 [fonttools]
   --------------------- ------------------  8/15 [fonttools]
   --------------------- ------------------  8/15 [fonttools]
   --------------------- ------------------  8/15 [fonttools]
   --------------------- ------------------  8/15 [fonttools]
   --------------------- ------------------  8/15 [fonttools]
   --------------------- ------------------  8/15 [fonttools]
   --------------------- ------------------  8/15 [fonttools]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]
   -------------------------- ------------- 10/15 [pandas]

In [7]:
%pip install plotly

Defaulting to user installation because normal site-packages is not writeable
Collecting plotly
  Downloading plotly-6.9.0-py3-none-any.whl.metadata (9.0 kB)
Collecting narwhals>=1.15.1 (from plotly)
  Downloading narwhals-2.23.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: packaging in C:\Users\SMIT\AppData\Roaming\Python\Python314\site-packages (from plotly) (26.2)
Downloading plotly-6.9.0-py3-none-any.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.9 MB 2.5 MB/s eta 0:00:04
   ------- -------------------------------- 1.8/9.9 MB 4.1 MB/s eta 0:00:02
   ----------------- ---------------------- 4.5/9.9 MB 6.8 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 12.2 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 11.6 MB/s  0:00:01
Downloading narwhals-2.23.0-py3-none-any.whl (458 kB)
Installing collected packages: narwhals, plotly

   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   ---------------------------------------- 2/2 [plotly]

Successfully installed narwhals-2.23.0 plotly-6.9.0
Note: you may need to restart the kernel to use updated packages.

In [34]:
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pandas_datareader as web
import plotly.express as px
import datetime

In [10]:
year = 1

In [11]:
end = datetime.datetime.today()
end

datetime.datetime(2026, 7, 12, 16, 45, 47, 53080)

In [13]:
# start = datetime.date(2025,07,12)
start = datetime.date(datetime.date.today().year - year, datetime.date.today().month, datetime.date.today().day)

In [14]:
start

datetime.date(2025, 7, 12)

In [15]:
sp500 = web.DataReader(["sp500"], 'fred', start, end)
sp500.tail()

              sp500
DATE
2026-07-06  7537.43
2026-07-07  7503.85
2026-07-08  7482.71
2026-07-09  7543.64
2026-07-10  7575.39

In [16]:
stocks_list = ["TSLA","AAPL","AMZN","GOOGL"]

In [ ]:
stocks_df = pd.DataFrame()

for stock in stocks_list:
    data = yf.download(stock, period = f'{year}y')
    stocks_df[stock] = data["Close"]

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [18]:
stocks_df.head()

                  TSLA        AAPL        AMZN       GOOGL
Date
2025-07-11  313.510010  210.325607  225.020004  179.677429
2025-07-14  316.899994  207.795624  225.690002  181.043518
2025-07-15  310.779999  208.283691  226.350006  181.482285
2025-07-16  321.670013  209.329559  223.190002  182.449509
2025-07-17  319.410004  209.190109  223.880005  183.057785

In [19]:
stocks_df.reset_index(inplace=True)

In [20]:
stocks_df

          Date        TSLA        AAPL        AMZN       GOOGL
0   2025-07-11  313.510010  210.325607  225.020004  179.677429
1   2025-07-14  316.899994  207.795624  225.690002  181.043518
2   2025-07-15  310.779999  208.283691  226.350006  181.482285
3   2025-07-16  321.670013  209.329559  223.190002  182.449509
4   2025-07-17  319.410004  209.190109  223.880005  183.057785
..         ...         ...         ...         ...         ...
246 2026-07-06  419.769989  312.660004  244.160004  366.459991
247 2026-07-07  402.899994  310.660004  245.979996  367.029999
248 2026-07-08  394.059998  313.390015  243.619995  361.920013
249 2026-07-09  406.549988  316.220001  247.039993  358.890015
250 2026-07-10  407.760010  315.320007  245.339996  357.179993

[251 rows x 5 columns]

In [22]:
sp500.reset_index(inplace=True)

In [23]:
sp500

          DATE    sp500
0   2025-07-14  6268.56
1   2025-07-15  6243.76
2   2025-07-16  6263.70
3   2025-07-17  6297.36
4   2025-07-18  6296.79
..         ...      ...
255 2026-07-06  7537.43
256 2026-07-07  7503.85
257 2026-07-08  7482.71
258 2026-07-09  7543.64
259 2026-07-10  7575.39

[260 rows x 2 columns]

In [24]:
sp500.rename(columns={"DATE" : "Date"},inplace=True)

In [25]:
sp500

          Date    sp500
0   2025-07-14  6268.56
1   2025-07-15  6243.76
2   2025-07-16  6263.70
3   2025-07-17  6297.36
4   2025-07-18  6296.79
..         ...      ...
255 2026-07-06  7537.43
256 2026-07-07  7503.85
257 2026-07-08  7482.71
258 2026-07-09  7543.64
259 2026-07-10  7575.39

[260 rows x 2 columns]

In [28]:
data = pd.merge(stocks_df, sp500, on="Date", how="inner")

In [30]:
data.set_index("Date",inplace=True)

In [31]:
data

                  TSLA        AAPL        AMZN       GOOGL    sp500
Date
2025-07-14  316.899994  207.795624  225.690002  181.043518  6268.56
2025-07-15  310.779999  208.283691  226.350006  181.482285  6243.76
2025-07-16  321.670013  209.329559  223.190002  182.449509  6263.70
2025-07-17  319.410004  209.190109  223.880005  183.057785  6297.36
2025-07-18  329.649994  210.345505  226.130005  184.533569  6296.79
...                ...         ...         ...         ...      ...
2026-07-06  419.769989  312.660004  244.160004  366.459991  7537.43
2026-07-07  402.899994  310.660004  245.979996  367.029999  7503.85
2026-07-08  394.059998  313.390015  243.619995  361.920013  7482.71
2026-07-09  406.549988  316.220001  247.039993  358.890015  7543.64
2026-07-10  407.760010  315.320007  245.339996  357.179993  7575.39

[250 rows x 5 columns]

###  Functions to plot interactive plotly charts

In [80]:
def interactive_plot(df):
        fig = px.line()
        for i in df.columns:
            fig.add_scatter(x=df.index, y=df[i], name=i)
        fig.update_layout(
            width = 900,
            height = 700,
            margin = dict(l = 20, r = 20, t = 50, b = 20),
            legend = dict(
                orientation = "h",
                yanchor = "bottom",
                y = 1.02,
                xanchor = "right",
                x = 1
            ) 
        )
        return fig

In [81]:
interactive_plot(data)

In [82]:
data_normalized = data/data.max()

In [83]:
data_normalized

                TSLA      AAPL      AMZN     GOOGL     sp500
Date
2025-07-14  0.646893  0.657124  0.820721  0.449932  0.823750
2025-07-15  0.634400  0.658667  0.823121  0.451023  0.820492
2025-07-16  0.656630  0.661974  0.811630  0.453426  0.823112
2025-07-17  0.652017  0.661533  0.814139  0.454938  0.827535
2025-07-18  0.672920  0.665187  0.822321  0.458606  0.827460
...              ...       ...       ...       ...       ...
2026-07-06  0.856883  0.988742  0.887887  0.910732  0.990492
2026-07-07  0.822446  0.982417  0.894505  0.912148  0.986080
2026-07-08  0.804401  0.991051  0.885923  0.899449  0.983302
2026-07-09  0.829897  1.000000  0.898360  0.891919  0.991309
2026-07-10  0.832367  0.997154  0.892178  0.887669  0.995481

[250 rows x 5 columns]

In [84]:
interactive_plot(data_normalized)