In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("insurance.csv")

In [3]:
df

,age,sex,bmi,children,smoker,region,charges,friends,enemies,chips,fries,ramen,toportyu
0,19,female,NaN,0,yes,southwest,16884.92400,5,3,7,5,3,6
1,18,male,33.770,1,no,southeast,1725.55230,0,1,4,4,4,3
2,28,male,33.000,3,no,southeast,4449.46200,9,3,5,2,1,3
3,33,male,22.705,0,no,northwest,21984.47061,5,10,4,3,2,4
4,32,male,28.880,0,no,northwest,3866.85520,4,3,4,4,1,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,4,2,2,3,1,6
1334,18,female,31.920,0,no,northeast,2205.98080,6,2,7,6,4,6
1335,18,female,36.850,0,no,southeast,1629.83350,10,9,5,6,2,5
1336,21,female,25.800,0,no,southwest,2007.94500,2,6,6,3,5,2
1337,61,female,29.070,0,yes,northwest,29141.36030,10,7,1,7,3,7

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   str
 2   bmi       1327 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   str
 5   region    1338 non-null   str
 6   charges   1338 non-null   float64
 7   friends   1338 non-null   int64
 8   enemies   1338 non-null   int64
 9   chips     1338 non-null   int64
 10  fries     1338 non-null   int64
 11  ramen     1338 non-null   int64
 12  toportyu  1338 non-null   int64
dtypes: float64(2), int64(8), str(3)
memory usage: 136.0 KB

In [5]:
df.drop(columns=["friends","enemies","chips","fries","ramen","toportyu"],inplace=True)

In [6]:
df

      age     sex     bmi  children smoker     region      charges
0      19  female     NaN         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [7]:
df.isnull().sum()

age          0
sex          0
bmi         11
children     0
smoker       0
region       0
charges      0
dtype: int64

In [10]:
df.bmi = df.bmi.fillna(df.bmi.mean())

In [11]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [12]:
df.head()

   age     sex        bmi  children smoker     region      charges
0   19  female  30.667841         0    yes  southwest  16884.92400
1   18    male  33.770000         1     no  southeast   1725.55230
2   28    male  33.000000         3     no  southeast   4449.46200
3   33    male  22.705000         0     no  northwest  21984.47061
4   32    male  28.880000         0     no  northwest   3866.85520

In [14]:
%pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.9.0-cp311-cp311-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\users\smit\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (2.4.6)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp311-cp311-win_amd64.whl.metadata (60 kB)
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ------ --------------------------------- 10.2/61.0 kB ? eta -:--:--
     ------------------- ------------------ 30.7/61.0 kB 435.7 kB/s eta 0:00:01
     ------------------------- ------------ 41.0/61.0 kB 326.8 kB/s eta 0:00:01
     -------------------------------------- 61.0/61.0 kB 405.7 kB/s eta 0:00:00
Collecting joblib>=1.4.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\smit\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (2.24.0)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.9.0-cp311-cp311-win_amd64.whl (8.3 MB)
   ---------------------------------------- 0.0/8.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.3 MB 1.9 MB/s eta 0:00:05
   ---------------------------------------- 0.1/8.3 MB 1.7 MB/s eta 0:00:05
    --------------------------------------- 0.1/8.3 MB 901.1 kB/s eta 0:00:10
   - -------------------------------------- 0.2/8.3 MB 1.3 MB/s eta 0:00:07
   - -------------------------------------- 0.2/8.3 MB 1.3 MB/s eta 0:00:07
   - -------------------------------------- 0.4/8.3 MB 1.3 MB/s eta 0:00:07
   -- ------------------------------------- 0.5/8.3 MB 1.7 MB/s eta 0:00:05
   -- ------------------------------------- 0.5/8.3 MB 1.5 MB/s eta 0:00:06
   ---- ----------------------------------- 0.9/8.3 MB 2.2 MB/s eta 0:00:04
   ---- ----------------------------------- 1.0/8.3 MB 2.4 MB/s eta 0:00:04
   ------ --------------------------------- 1.3/8.3 MB 2.8 MB/s eta 0:00:03
   --------- ------------------------------ 2.0/8.3 MB 3.8 MB/s eta 0:00:02
   ---------- ----------------------------- 2.1/8.3 MB 3.7 MB/s eta 0:00:02
   --------------- ------------------------ 3.3/8.3 MB 5.2 MB/s eta 0:00:01
   ------------------- -------------------- 4.1/8.3 MB 6.3 MB/s eta 0:00:01
   ------------------------- -------------- 5.3/8.3 MB 7.4 MB/s eta 0:00:01
   -------------------------------------- - 7.9/8.3 MB 10.3 MB/s eta 0:00:01
   ---------------------------------------  8.2/8.3 MB 10.5 MB/s eta 0:00:01
   ---------------------------------------  8.2/8.3 MB 10.5 MB/s eta 0:00:01
   ---------------------------------------  8.2/8.3 MB 10.5 MB/s eta 0:00:01
   ---------------------------------------  8.2/8.3 MB 10.5 MB/s eta 0:00:01
   ---------------------------------------  8.2/8.3 MB 10.5 MB/s eta 0:00:01
   ---------------------------------------  8.2/8.3 MB 10.5 MB/s eta 0:00:01
   ---------------------------------------  8.2/8.3 MB 10.5 MB/s eta 0:00:01
   ---------------------------------------  8.2/8.3 MB 10.5 MB/s eta 0:00:01
   ---------------------------------------  8.3/8.3 MB 7.1 MB/s eta 0:00:01
   ---------------------------------------  8.3/8.3 MB 7.1 MB/s eta 0:00:01
   ---------------------------------------  8.3/8.3 MB 7.1 MB/s eta 0:00:01
   ---------------------------------------  8.3/8.3 MB 7.1 MB/s eta 0:00:01
   ---------------------------------------  8.3/8.3 MB 7.1 MB/s eta 0:00:01
   ---------------------------------------  8.3/8.3 MB 5.9 MB/s eta 0:00:01
   ---------------------------------------  8.3/8.3 MB 5.9 MB/s eta 0:00:01
   ---------------------------------------  8.3/8.3 MB 5.9 MB/s eta 0:00:01
   ---------------------------------------- 8.3/8.3 MB 5.3 MB/s eta 0:00:00
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading scipy-1.17.1-cp311-cp311-win_amd64.whl (36.6 MB)
   ---------------------------------------- 0.0/36.6 MB ? eta -:--:--
   -- ------------------------------------- 2.6/36.6 MB 56.8 MB/s eta 0:00:01
   ----- ---------------------------------- 5.3/36.6 MB 57.3 MB/s eta 0:00:01
   ------ --------------------------------- 6.0/36.6 MB 48.1 MB/s eta 0:00:01
   ------ --------------------------------- 6.0/36.6 MB 48.1 MB/s eta 0:00:01
   ------ --------------------------------- 6.0/36.6 MB 48.1 MB/s eta 0:00:01
   --------- ------------------------------ 8.7/36.6 MB 32.7 MB/s eta 0:00:01
   ---------- ----------------------------- 9.8/36.6 MB 34.9 MB/s eta 0:00:01
   ------------- -------------------------- 12.5/36.6 MB 31.2 MB/s eta 0:00:01
   ------------- -------------------------- 12.6/36.6 MB 29.7 MB/s eta 0:00:01
   ------------- -------------------------- 12.6/36.6 MB 29.7 MB/s eta 0:00:01
   ------------- -------------------------- 12.6/36.6 MB 29.7 MB/s eta 0:00:01
   -------------- ------------------------- 13.2/36.6 MB 20.5 MB/s eta 0:00:02
   -------------- ------------------------- 13.2/36.6 MB 20.5 MB/s eta 0:00:02
   -------------- ------------------------- 13.2/36.6 MB 20.5 MB/s eta 0:00:02
   -------------- ------------------------- 13.2/36.6 MB 20.5 MB/s eta 0:00:02
   --------------- ------------------------ 14.4/36.6 MB 15.2 MB/s eta 0:00:02
   -------------------- ------------------- 18.6/36.6 MB 21.1 MB/s eta 0:00:01
   -------------------- ------------------- 18.6/36.6 MB 21.1 MB/s eta 0:00:01
   -------------------- ------------------- 18.8/36.6 MB 17.7 MB/s eta 0:00:02
   --------------------- ------------------ 19.3/36.6 MB 16.8 MB/s eta 0:00:02
   --------------------- ------------------ 19.3/36.6 MB 16.8 MB/s eta 0:00:02
   --------------------- ------------------ 19.3/36.6 MB 16.8 MB/s eta 0:00:02
   ------------------------- -------------- 23.4/36.6 MB 20.5 MB/s eta 0:00:01
   ------------------------- -------------- 23.7/36.6 MB 29.7 MB/s eta 0:00:01
   -------------------------- ------------- 24.4/36.6 MB 26.2 MB/s eta 0:00:01
   --------------------------- ------------ 25.2/36.6 MB 21.8 MB/s eta 0:00:01
   ---------------------------- ----------- 25.7/36.6 MB 20.5 MB/s eta 0:00:01
   ----------------------------- ---------- 26.7/36.6 MB 18.7 MB/s eta 0:00:01
   ----------------------------- ---------- 26.7/36.6 MB 18.7 MB/s eta 0:00:01
   ------------------------------ --------- 27.5/36.6 MB 16.8 MB/s eta 0:00:01
   ------------------------------- -------- 29.2/36.6 MB 20.5 MB/s eta 0:00:01
   ------------------------------- -------- 29.2/36.6 MB 20.5 MB/s eta 0:00:01
   ------------------------------- -------- 29.2/36.6 MB 20.5 MB/s eta 0:00:01
   ---------------------------------- ----- 31.4/36.6 MB 19.8 MB/s eta 0:00:01
   ---------------------------------- ----- 31.7/36.6 MB 18.7 MB/s eta 0:00:01
   ---------------------------------- ----- 31.9/36.6 MB 16.8 MB/s eta 0:00:01
   ----------------------------------- ---- 32.4/36.6 MB 15.6 MB/s eta 0:00:01
   ----------------------------------- ---- 32.8/36.6 MB 14.5 MB/s eta 0:00:01
   ------------------------------------ --- 33.2/36.6 MB 13.6 MB/s eta 0:00:01
   ------------------------------------ --- 33.6/36.6 MB 13.4 MB/s eta 0:00:01
   ------------------------------------- -- 33.9/36.6 MB 13.1 MB/s eta 0:00:01
   ------------------------------------- -- 34.4/36.6 MB 12.6 MB/s eta 0:00:01
   -------------------------------------- - 34.8/36.6 MB 12.4 MB/s eta 0:00:01
   -------------------------------------- - 35.2/36.6 MB 12.1 MB/s eta 0:00:01
   -------------------------------------- - 35.6/36.6 MB 12.1 MB/s eta 0:00:01
   ---------------------------------------  36.0/36.6 MB 11.9 MB/s eta 0:00:01
   ---------------------------------------  36.4/36.6 MB 11.5 MB/s eta 0:00:01
   ---------------------------------------  36.6/36.6 MB 11.3 MB/s eta 0:00:01
   ---------------------------------------  36.6/36.6 MB 11.3 MB/s eta 0:00:01
   ---------------------------------------  36.6/36.6 MB 11.3 MB/s eta 0:00:01
   ---------------------------------------  36.6/36.6 MB 11.3 MB/s eta 0:00:01
   ---------------------------------------  36.6/36.6 MB 11.3 MB/s eta 0:00:01
   ---------------------------------------  36.6/36.6 MB 11.3 MB/s eta 0:00:01
   ---------------------------------------  36.6/36.6 MB 11.3 MB/s eta 0:00:01
   ---------------------------------------  36.6/36.6 MB 11.3 MB/s eta 0:00:01
   ---------------------------------------  36.6/36.6 MB 11.3 MB/s eta 0:00:01
   ---------------------------------------  36.6/36.6 MB 11.3 MB/s eta 0:00:01
   ---------------------------------------  36.6/36.6 MB 11.3 MB/s eta 0:00:01
   ---------------------------------------  36.6/36.6 MB 11.3 MB/s eta 0:00:01
   ---------------------------------------  36.6/36.6 MB 11.3 MB/s eta 0:00:01
   ---------------------------------------  36.6/36.6 MB 11.3 MB/s eta 0:00:01
   ---------------------------------------- 36.6/36.6 MB 6.6 MB/s eta 0:00:00
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
Successfully installed joblib-1.5.3 scikit-learn-1.9.0 scipy-1.17.1 threadpoolctl-3.6.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [15]:
from sklearn.preprocessing import OneHotEncoder

In [16]:
encoder  =  OneHotEncoder()

In [17]:
encoded_categories = encoder.fit_transform(df.select_dtypes('O'))

C:\Users\SMIT\AppData\Local\Temp\ipykernel_21096\4136675267.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  encoded_categories = encoder.fit_transform(df.select_dtypes('O'))

In [23]:
encoder.get_feature_names_out()

array(['sex_female', 'sex_male', 'smoker_no', 'smoker_yes',
       'region_middle', 'region_northeast', 'region_northwest',
       'region_southeast', 'region_southwest'], dtype=object)

In [21]:
encoded_categories = encoded_categories.toarray()

In [22]:
type(encoded_categories)

numpy.ndarray

In [25]:
encoded_categories = pd.DataFrame(data=encoded_categories, columns=encoder.get_feature_names_out())

In [26]:
encoded_categories

,sex_female,sex_male,smoker_no,smoker_yes,region_middle,region_northeast,region_northwest,region_southeast,region_southwest
0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
4,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
1333,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
1334,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
1335,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1336,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
1337,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0

In [27]:
numerical_data = df.select_dtypes('number')
numerical_data

      age        bmi  children      charges
0      19  30.667841         0  16884.92400
1      18  33.770000         1   1725.55230
2      28  33.000000         3   4449.46200
3      33  22.705000         0  21984.47061
4      32  28.880000         0   3866.85520
...   ...        ...       ...          ...
1333   50  30.970000         3  10600.54830
1334   18  31.920000         0   2205.98080
1335   18  36.850000         0   1629.83350
1336   21  25.800000         0   2007.94500
1337   61  29.070000         0  29141.36030

[1338 rows x 4 columns]

In [29]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [30]:
scaled_numerical_data = scaler.fit_transform(numerical_data)

In [31]:
scaled_numerical_data

array([[0.02195609, 0.39569118, 0.        , 0.25161076],
       [0.02095808, 0.47914985, 0.2       , 0.00963595],
       [0.03093812, 0.45843422, 0.6       , 0.05311516],
       ...,
       [0.02095808, 0.56201238, 0.        , 0.00810808],
       [0.0239521 , 0.26472962, 0.        , 0.01414352],
       [0.06387226, 0.35270379, 0.        , 0.44724873]], shape=(1338, 4))

In [33]:
scaler.get_feature_names_out()

array(['age', 'bmi', 'children', 'charges'], dtype=object)

In [34]:
numerical_data = pd.DataFrame(data=scaled_numerical_data, columns=scaler.get_feature_names_out())

In [35]:
numerical_data

           age       bmi  children   charges
0     0.021956  0.395691       0.0  0.251611
1     0.020958  0.479150       0.2  0.009636
2     0.030938  0.458434       0.6  0.053115
3     0.035928  0.181464       0.0  0.333010
4     0.034930  0.347592       0.0  0.043816
...        ...       ...       ...       ...
1333  0.052894  0.403820       0.6  0.151299
1334  0.020958  0.429379       0.0  0.017305
1335  0.020958  0.562012       0.0  0.008108
1336  0.023952  0.264730       0.0  0.014144
1337  0.063872  0.352704       0.0  0.447249

[1338 rows x 4 columns]

In [36]:
df = pd.concat([numerical_data,encoded_categories],axis=1)

In [37]:
df

,age,bmi,children,charges,sex_female,sex_male,smoker_no,smoker_yes,region_middle,region_northeast,region_northwest,region_southeast,region_southwest
0,0.021956,0.395691,0.0,0.251611,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1,0.020958,0.479150,0.2,0.009636,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.030938,0.458434,0.6,0.053115,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.035928,0.181464,0.0,0.333010,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
4,0.034930,0.347592,0.0,0.043816,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1333,0.052894,0.403820,0.6,0.151299,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
1334,0.020958,0.429379,0.0,0.017305,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
1335,0.020958,0.562012,0.0,0.008108,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1336,0.023952,0.264730,0.0,0.014144,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
1337,0.063872,0.352704,0.0,0.447249,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0

In [45]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score , mean_squared_error

In [39]:
X = df.drop('charges',axis=1)
y = df.charges

In [40]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [41]:
model = LinearRegression()

In [42]:
model.fit(X_train,y_train)

LinearRegression()

In [43]:
y_pred_train = model.predict(X_train)

In [48]:
mean_squared_error(y_train,y_pred_train)

0.012681425386366985

In [49]:
r2_score(y_train,y_pred_train)

0.660182095365472

In [50]:
y_pred_test = model.predict(X_test)

In [ ]:
mean_squared_error(y_test,y_pred_test)

0.010967219388780591

In [52]:
r2_score(y_test,y_pred_test)

0.7064293323990556

# Applying Polynomial Regression

In [53]:
from sklearn.preprocessing import PolynomialFeatures

In [54]:
poly = PolynomialFeatures(degree=2, include_bias=True)
X_poly = poly.fit_transform(X)

In [55]:
X = pd.DataFrame(data=X_poly, columns=poly.get_feature_names_out())
X

,1,age,bmi,children,sex_female,sex_male,smoker_no,smoker_yes,region_middle,region_northeast,...,region_northeast^2,region_northeast region_northwest,region_northeast region_southeast,region_northeast region_southwest,region_northwest^2,region_northwest region_southeast,region_northwest region_southwest,region_southeast^2,region_southeast region_southwest,region_southwest^2
0,1.0,0.021956,0.395691,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,1.0,0.020958,0.479150,0.2,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,1.0,0.030938,0.458434,0.6,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,1.0,0.035928,0.181464,0.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,1.0,0.034930,0.347592,0.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1333,1.0,0.052894,0.403820,0.6,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1334,1.0,0.020958,0.429379,0.0,1.0,0.0,1.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1335,1.0,0.020958,0.562012,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1336,1.0,0.023952,0.264730,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1337,1.0,0.063872,0.352704,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [56]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [57]:
lr = LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [58]:
y_pred_train = lr.predict(X_train)

In [59]:
r2_score(y_train,y_pred_train)

0.8254954224541238

In [60]:
mean_squared_error(y_train,y_pred_train)

0.006512213598949571

In [61]:
y_pred_test = lr.predict(X_test)

In [62]:
r2_score(y_test,y_pred_test)

0.8492114156437235

In [63]:
mean_squared_error(y_test,y_pred_test)

0.005633163215770859