In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("advertising.xlsx")

In [3]:
df

        TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3   12.0
3    151.5   41.3       58.5   16.5
4    180.8   10.8       58.4   17.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

[200 rows x 4 columns]

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   TV         200 non-null    float64
 1   Radio      200 non-null    float64
 2   Newspaper  200 non-null    float64
 3   Sales      200 non-null    float64
dtypes: float64(4)
memory usage: 6.4 KB

In [5]:
df.isnull().sum()

TV           0
Radio        0
Newspaper    0
Sales        0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.head()

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [8]:
from sklearn.preprocessing import MinMaxScaler

In [9]:
scaler = MinMaxScaler()

In [12]:
x = df.drop(columns="Sales")

In [13]:
x

        TV  Radio  Newspaper
0    230.1   37.8       69.2
1     44.5   39.3       45.1
2     17.2   45.9       69.3
3    151.5   41.3       58.5
4    180.8   10.8       58.4
..     ...    ...        ...
195   38.2    3.7       13.8
196   94.2    4.9        8.1
197  177.0    9.3        6.4
198  283.6   42.0       66.2
199  232.1    8.6        8.7

[200 rows x 3 columns]

In [14]:
scaled_df = scaler.fit_transform(x)

In [15]:
scaled_df

array([[0.77578627, 0.76209677, 0.60598065],
       [0.1481231 , 0.79233871, 0.39401935],
       [0.0557998 , 0.92540323, 0.60686016],
       [0.50997633, 0.83266129, 0.51187335],
       [0.60906324, 0.21774194, 0.51099384],
       [0.02705445, 0.9858871 , 0.65699208],
       [0.19208657, 0.66129032, 0.20404573],
       [0.4041258 , 0.39516129, 0.09938434],
       [0.02671627, 0.04233871, 0.00615655],
       [0.67331755, 0.05241935, 0.18381706],
       [0.2211701 , 0.11693548, 0.21020229],
       [0.72370646, 0.48387097, 0.03254178],
       [0.07811972, 0.70766129, 0.5769569 ],
       [0.32735881, 0.15322581, 0.06068602],
       [0.68785932, 0.66330645, 0.40193492],
       [0.65843761, 0.96169355, 0.46262093],
       [0.22691917, 0.73790323, 1.        ],
       [0.94927291, 0.7983871 , 0.48812665],
       [0.2316537 , 0.41330645, 0.15831135],
       [0.49577274, 0.48185484, 0.16534741],
       [0.73621914, 0.55846774, 0.46701847],
       [0.80047345, 0.10282258, 0.20404573],
       [0.04227257, 0.32056452, 0.43359719],
       [0.76969902, 0.34072581, 0.22779244],
       [0.20831924, 0.25403226, 0.15831135],
       [0.8867095 , 0.07056452, 0.16886544],
       [0.4808928 , 0.59072581, 0.10817942],
       [0.80960433, 0.33669355, 0.19876869],
       [0.83902604, 0.54637097, 0.19876869],
       [0.23638823, 0.32258065, 0.35620053],
       [0.98816368, 0.57056452, 0.37730871],
       [0.37943862, 0.35080645, 0.33685136],
       [0.32634427, 0.03024194, 0.26121372],
       [0.89584038, 0.40322581, 0.        ],
       [0.32127156, 0.02822581, 0.06244503],
       [0.98072371, 0.08266129, 0.07211961],
       [0.90023673, 0.88306452, 0.04133685],
       [0.25025364, 0.99596774, 0.39929639],
       [0.14338857, 0.53830645, 0.3060686 ],
       [0.76868448, 0.76008065, 0.27880387],
       [0.68244843, 0.44959677, 0.27528584],
       [0.59621238, 0.6733871 , 0.33773087],
       [0.99053094, 0.55846774, 0.01319261],
       [0.69732837, 0.16935484, 0.22955145],
       [0.08251606, 0.51814516, 0.37818821],
       [0.58978695, 0.45362903, 0.27440633],
       [0.30098072, 0.19959677, 0.31134565],
       [0.80892797, 0.83669355, 0.16007036],
       [0.76597903, 0.31854839, 0.43623571],
       [0.22387555, 0.2358871 , 0.32102023],
       [0.67331755, 0.0625    , 0.30167106],
       [0.33716605, 0.19354839, 0.02902375],
       [0.72945553, 0.84072581, 0.34564644],
       [0.61515049, 0.93145161, 0.51363237],
       [0.88603314, 0.58064516, 0.13720317],
       [0.67027393, 0.99596774, 0.52506596],
       [0.02231992, 0.56653226, 0.36147757],
       [0.4582347 , 0.38709677, 0.14335972],
       [0.71051742, 1.        , 0.3289358 ],
       [0.71017924, 0.59475806, 0.07915567],
       [0.17855935, 0.04032258, 0.18557608],
       [0.88129861, 0.8608871 , 0.47845207],
       [0.80689888, 0.3125    , 0.23746702],
       [0.3449442 , 0.59677419, 0.07124011],
       [0.44098749, 0.86290323, 0.25153914],
       [0.23097734, 0.1875    , 0.00527704],
       [0.10415962, 0.49596774, 0.01671064],
       [0.4687183 , 0.29233871, 0.08707124],
       [0.80047345, 0.55443548, 0.0941073 ],
       [0.73080825, 0.88508065, 0.23658751],
       [0.67095029, 0.61693548, 0.33773087],
       [0.36895502, 0.28830645, 0.27616535],
       [0.08826513, 0.66532258, 0.16710642],
       [0.43523842, 0.11491935, 0.27264732],
       [0.71931011, 0.49596774, 0.11257696],
       [0.05478526, 0.88104839, 0.78364116],
       [0.0906324 , 0.03225806, 0.17941953],
       [0.40514034, 0.57459677, 0.12225154],
       [0.01589449, 0.60282258, 0.08003518],
       [0.38992222, 0.15524194, 0.2005277 ],
       [0.25600271, 0.53830645, 0.19349164],
       [0.80858979, 0.08266129, 0.32189974],
       [0.25228272, 0.40927419, 0.28320141],
       [0.22894826, 0.89717742, 0.31046614],
       [0.71964829, 0.86693548, 0.294635  ],
       [0.65099763, 0.37096774, 0.57519789],
       [0.25566452, 0.55443548, 0.13808267],
       [0.37199865, 0.81854839, 0.5532102 ],
       [0.2962462 , 0.5141129 , 0.64291996],
       [0.36895502, 0.96370968, 0.44942832],
       [0.45180927, 0.09879032, 0.07915567],
       [0.09435238, 0.03024194, 0.28759894],
       [0.73385188, 0.67540323, 0.51627089],
       [0.84612783, 0.7358871 , 0.63324538],
       [0.36083869, 0.28225806, 0.09322779],
       [0.54988164, 0.63709677, 0.46262093],
       [0.66587758, 0.07056452, 0.04925242],
       [0.62292864, 0.4233871 , 0.19085312],
       [0.9773419 , 0.85282258, 0.44766931],
       [0.45485289, 0.84072581, 0.40105541],
       [0.74974636, 0.08669355, 0.4353562 ],
       [1.        , 0.73185484, 0.88478452],
       [0.94521474, 0.20362903, 0.18557608],
       [0.63307406, 0.34677419, 0.15479332],
       [0.8031789 , 0.69153226, 0.04397537],
       [0.46398377, 0.93548387, 0.51627089],
       [0.08217788, 0.22177419, 0.2585752 ],
       [0.30334799, 0.00604839, 0.20140721],
       [0.04193439, 0.00806452, 0.22251539],
       [0.86134596, 0.54233871, 0.04573439],
       [0.7612445 , 0.16532258, 0.4942832 ],
       [0.81501522, 0.76612903, 0.20140721],
       [0.59181603, 0.31048387, 0.01846966],
       [0.70645925, 0.41532258, 0.09146878],
       [0.26208996, 0.94354839, 0.30079156],
       [0.25160636, 0.70564516, 0.46086192],
       [0.46838011, 0.28830645, 0.22251539],
       [0.25600271, 0.01612903, 0.12752858],
       [0.42272574, 0.74395161, 0.6939314 ],
       [0.06323977, 0.32258065, 0.19349164],
       [0.47548191, 0.54032258, 0.40369393],
       [0.06121069, 0.4375    , 0.44063325],
       [0.75515725, 0.0483871 , 0.13456464],
       [0.41393304, 0.69758065, 0.1064204 ],
       [0.77375719, 0.65120968, 0.64995602],
       [0.29252621, 0.23790323, 0.22515391],
       [0.02401082, 0.78427419, 0.44239226],
       [0.26885357, 0.        , 0.07827617],
       [0.74264457, 0.98790323, 0.02550572],
       [0.19918837, 0.24193548, 0.3764292 ],
       [0.        , 0.7983871 , 0.07387863],
       [0.89448766, 0.05846774, 0.37554969],
       [0.02603991, 0.5483871 , 0.01583113],
       [0.74095367, 0.67540323, 0.39401935],
       [0.12242137, 0.77822581, 0.57431838],
       [0.16097396, 0.94758065, 0.07211961],
       [0.08420697, 0.78629032, 0.07915567],
       [0.92323301, 0.58266129, 0.52242744],
       [0.14305039, 0.52217742, 0.17766051],
       [0.62292864, 0.88508065, 0.0123131 ],
       [0.24585729, 0.34274194, 0.11081794],
       [0.65268854, 0.71370968, 0.66226913],
       [0.74332093, 0.66935484, 0.33069481],
       [0.35136963, 0.11491935, 0.29991205],
       [0.32296246, 0.2983871 , 0.33948989],
       [0.4721001 , 0.03830645, 0.07651715],
       [0.80960433, 0.14717742, 0.07387863],
       [0.82008793, 0.98790323, 0.38698329],
       [0.12614136, 0.8125    , 0.10202287],
       [0.14879946, 0.52016129, 0.17854002],
       [0.94690565, 0.28024194, 0.32277924],
       [0.40683125, 0.16935484, 0.42568162],
       [0.66587758, 0.46975806, 0.12225154],
       [0.57693608, 0.80040323, 0.3289358 ],
       [0.63273588, 0.42540323, 0.08091469],
       [0.01149814, 0.23387097, 0.0474934 ],
       [0.31518431, 0.87701613, 0.44151275],
       [0.50422726, 0.02620968, 0.21108179],
       [0.03719986, 0.74395161, 0.39489886],
       [0.44301657, 0.37096774, 0.30167106],
       [0.58099425, 0.36491935, 0.26737027],
       [0.2874535 , 0.72177419, 0.43095866],
       [0.63476496, 0.36491935, 0.22251539],
       [0.550558  , 0.74193548, 0.06244503],
       [0.39398039, 0.29637097, 0.04485488],
       [0.79066622, 0.06854839, 0.74318382],
       [0.05816706, 0.75806452, 0.18733509],
       [0.69699019, 0.10483871, 0.16798593],
       [0.72607372, 0.47580645, 0.50395778],
       [0.95908015, 0.21370968, 0.05364996],
       [0.16672303, 0.23387097, 0.15919085],
       [0.5539398 , 0.42137097, 0.41424802],
       [0.06391613, 0.40524194, 0.14687775],
       [0.56712885, 0.14314516, 0.10993843],
       [0.74974636, 0.06854839, 0.11257696],
       [0.93405479, 0.9858871 , 0.3649956 ],
       [0.83767332, 0.60887097, 0.1759015 ],
       [0.5732161 , 0.15725806, 0.30694811],
       [0.93337842, 0.04637097, 0.20580475],
       [0.55765979, 0.2016129 , 0.15215479],
       [0.52722354, 0.05241935, 0.0703606 ],
       [0.73655732, 0.10887097, 0.23834653],
       [0.18769023, 0.11491935, 0.2585752 ],
       [0.97024011, 0.86693548, 0.62884785],
       [0.85593507, 0.42943548, 0.26121372],
       [0.69090294, 0.90927419, 0.16974494],
       [0.46939466, 0.04233871, 0.23131047],
       [0.64389584, 0.57862903, 0.15743184],
       [0.96482922, 0.28024194, 0.02990325],
       [0.06087251, 0.24395161, 0.20316623],
       [0.13121407, 0.82862903, 0.04837291],
       [0.25295908, 0.21774194, 0.05013193],
       [0.0557998 , 0.08266129, 0.27528584],
       [0.56171796, 0.84677419, 0.02902375],
       [0.50388908, 0.71774194, 0.05013193],
       [0.12681772, 0.07459677, 0.11873351],
       [0.31619885, 0.09879032, 0.06860158],
       [0.59621238, 0.1875    , 0.05364996],
       [0.95671288, 0.84677419, 0.57959543],
       [0.78254988, 0.1733871 , 0.07387863]])

In [16]:
scaled_df = pd.DataFrame(data=scaled_df, columns=scaler.get_feature_names_out())

In [17]:
scaled_df

           TV     Radio  Newspaper
0    0.775786  0.762097   0.605981
1    0.148123  0.792339   0.394019
2    0.055800  0.925403   0.606860
3    0.509976  0.832661   0.511873
4    0.609063  0.217742   0.510994
..        ...       ...        ...
195  0.126818  0.074597   0.118734
196  0.316199  0.098790   0.068602
197  0.596212  0.187500   0.053650
198  0.956713  0.846774   0.579595
199  0.782550  0.173387   0.073879

[200 rows x 3 columns]

In [19]:
df = pd.concat([scaled_df,df.Sales],axis=1)

In [20]:
df

           TV     Radio  Newspaper  Sales
0    0.775786  0.762097   0.605981   22.1
1    0.148123  0.792339   0.394019   10.4
2    0.055800  0.925403   0.606860   12.0
3    0.509976  0.832661   0.511873   16.5
4    0.609063  0.217742   0.510994   17.9
..        ...       ...        ...    ...
195  0.126818  0.074597   0.118734    7.6
196  0.316199  0.098790   0.068602   14.0
197  0.596212  0.187500   0.053650   14.8
198  0.956713  0.846774   0.579595   25.5
199  0.782550  0.173387   0.073879   18.4

[200 rows x 4 columns]

In [21]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score , mean_squared_error

In [22]:
X = df.drop('Sales',axis=1)
y = df.Sales

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [24]:
model = LinearRegression()

In [25]:
model.fit(X_train,y_train)

LinearRegression()

In [26]:
y_pred_train = model.predict(X_train)

In [27]:
mean_squared_error(y_train,y_pred_train)

2.839232660754425

In [28]:
r2_score(y_train,y_pred_train)

0.8919647339302077

In [29]:
y_pred_test = model.predict(X_test)

In [30]:
mean_squared_error(y_test,y_pred_test)

2.5416240362291496

In [31]:
r2_score(y_test,y_pred_test)

0.9091484341849799

# Applying Polynomial Regression

In [32]:
from sklearn.preprocessing import PolynomialFeatures

In [33]:
poly = PolynomialFeatures(degree=2, include_bias=True)
X_poly = poly.fit_transform(X)

In [34]:
X = pd.DataFrame(data=X_poly, columns=poly.get_feature_names_out())
X

,1,TV,Radio,Newspaper,TV^2,TV Radio,TV Newspaper,Radio^2,Radio Newspaper,Newspaper^2
0,1.0,0.775786,0.762097,0.605981,0.601844,0.591224,0.470111,0.580791,0.461816,0.367213
1,1.0,0.148123,0.792339,0.394019,0.021940,0.117364,0.058363,0.627801,0.312197,0.155251
2,1.0,0.055800,0.925403,0.606860,0.003114,0.051637,0.033863,0.856371,0.561590,0.368279
3,1.0,0.509976,0.832661,0.511873,0.260076,0.424638,0.261043,0.693325,0.426217,0.262014
4,1.0,0.609063,0.217742,0.510994,0.370958,0.132619,0.311228,0.047412,0.111265,0.261115
...,...,...,...,...,...,...,...,...,...,...
195,1.0,0.126818,0.074597,0.118734,0.016083,0.009460,0.015058,0.005565,0.008857,0.014098
196,1.0,0.316199,0.098790,0.068602,0.099982,0.031237,0.021692,0.009760,0.006777,0.004706
197,1.0,0.596212,0.187500,0.053650,0.355469,0.111790,0.031987,0.035156,0.010059,0.002878
198,1.0,0.956713,0.846774,0.579595,0.915300,0.810120,0.554506,0.717027,0.490786,0.335931
199,1.0,0.782550,0.173387,0.073879,0.612384,0.135684,0.057814,0.030063,0.012810,0.005458

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [36]:
lr = LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [37]:
y_pred_train = lr.predict(X_train)

In [38]:
r2_score(y_train,y_pred_train)

0.9238235326828357

In [39]:
mean_squared_error(y_train,y_pred_train)

2.0019640054208163

In [40]:
y_pred_test = lr.predict(X_test)

In [41]:
r2_score(y_test,y_pred_test)

0.9462913219526545

In [42]:
mean_squared_error(y_test,y_pred_test)

1.50253070329205